meta_product_name: "Papelitos"
meta_title: "Papelitos - Word games for fun!"
meta_description: "Papelitos is a fun game to play in group! Add some words, describe, mime and one-word description to them. Most of all, HAVE FUN!"
meta_image: "papelitos_logo.png" # should exist in `app/assets/images/`
